### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by derekbar90**
Update Catalyst definition

### CODE REVIEW

**Comment by d0whc3r** [comment]
@derekbar90 maybe you need to add using modules.yml file

**Comment by derekbar90** [comment]
Can you give me a little more insight? @d0whc3r 

There’s a lot more to this repo than pulling modules and using them.

**Comment by d0whc3r** [comment]
check this pr https://github.com/moleculerjs/awesome-moleculer/pull/27

**Comment by derekbar90** [comment]
Good looks I’ll update later today/tomorrow. Wasn’t aware of that update.

**Comment by AndreMaz** [comment]
@derekbar90 I'm closing this PR as I've updated the description on my side 😉 
@d0whc3r you are right, the updates must be done in `modules.yaml` because of https://github.com/moleculerjs/awesome-moleculer/pull/15

**Pull request closed without merging**
