### PR TITLE
add moleculer-pdf

### PR DESCRIPTION
**Pull request by intech**
Found on github. Anyone contact the author: https://github.com/olivmonnier

### CODE REVIEW

**Review by lucwj — APPROVED** [review]
Great :)

**Comment by AndreMaz** [comment]
Hey @intech can you add it to `modules.yml` instead of `README.md`?
We have the following flow:
58185096-4aa32080-7caa-11e9-8c58-95b35e9120e0
so new libs should be added `modules.yml`. Here is the [guide to add new modules](https://github.com/moleculerjs/awesome-moleculer/blob/master/PULL_REQUEST_TEMPLATE.md).

**Comment by intech** [comment]
@AndreMaz I saw the instructions, but there was no time. I thought one of the reviewers could add :wink:

**Comment by AndreMaz** [comment]
Ah ok ok. Then I will do it :wink:

**Comment by AndreMaz** [comment]
Closing. I've added it in https://github.com/moleculerjs/awesome-moleculer/commit/9edb8993237d4c7982a25f5e7af225fb86d63633.

**Pull request closed without merging**
